### ISSUE TITLE
I am getting error "{resizedFile: File, reason: TypeError: Cannot read property 'resizeCanvas' of undefined at http://localhost:4200/vendor.bund…, error: "PICA_ERROR"}"

### ISSUE THREAD

**Issue by reactionic127** [bergben/ng2-img-max#12]
when I try to resize the image using this module I am getting error like this.
{resizedFile: File, reason: TypeError: Cannot read property 'resizeCanvas' of undefined at http://localhost:4200/vendor.bund…, error: "PICA_ERROR"}
Anybody can help this problem?
Regards.

**Comment by kumar529** [comment]
Same problem

**Comment by hiepxanh** [comment]
same problem

**Comment by bergben** [comment]
Should be fixed now.

**Comment by hiepxanh** [comment]
YEAHHHHHHHH!!!!!!!!! Thanks you. I'm confusing one day and don't know what to do, I don't want to any else lib except your. I only get this error on resizing, after I install alot of module, i found this:

![image](https://user-images.githubusercontent.com/16970990/31392070-81d71c64-ae02-11e7-807d-f989eb1877d0.png)
and this line:
![image](https://user-images.githubusercontent.com/16970990/31392095-91b9c1a4-ae02-11e7-99f0-10354663e285.png)

**Comment by reactionic127** [comment]
@bergben
Thanks. It is working fine on my side.
I reinstalled the module and running my app and it is working properly.
Thanks for your help.
Regards.

**Comment by hiepxanh** [comment]
@reactionic127 what did you do ?

**Comment by reactionic127** [comment]
@hiepxanh 
I reinstalled this module using "npm install ng2-img-max --save"
and run "ng serve" on my app.
And it is working properly on my side.

**Comment by hiepxanh** [comment]
not resolve problem, still get err
