### ISSUE TITLE
Just update to v2.1.7 and the found some error

### ISSUE THREAD

**Issue by mene078** [bergben/ng2-img-max#17]
I got the error from my angular app, which just an update for today. Can not find any reference one for now.

`Error: Unexpected value 'Ng2ImgMaxModule' imported by the module 'AppModule'. Please add a @NgModule annotation`

**Comment by bogacg** [comment]
You've closed this issue but I'm seeing same error.

**Comment by bergben** [comment]
This indeed is a currently active bug, compare https://github.com/bergben/ng2-img-tools/issues/22

**Comment by mene078** [comment]
Yes, I closed this issue because I think that’s not the plugin bug. This issue happen with my action that tried to update from angular 4.5~ to 5.
Not just this lib had the issue, so I decided to downgrade my currently working project back to 4.5~.

**Comment by pegaltier** [comment]
Same bug since ng2-img-max 2.1.7 and 2.1.8 and angular 5.0.0 and 5.0.1
Temporary patch: use 2.1.6 version and patch with my solution: bergben/ng2-img-tools#15
https://github.com/bergben/ng2-img-max/issues/15

**Comment by dgaletto** [comment]
If you want to continue developing you can try  `ng serve --aot`

I'm busy this week, but I'll try to help with the error.

**Comment by bergben** [comment]
Hi guys, thanks for your patience. I just fixed this in 2.1.9.
Turns out you have to set typescript to version `2.4.2` in package.json, as never versions of TS don't work with ngc yet.
