### ISSUE TITLE
ng build : img-exif version 3 expected

### ISSUE THREAD

**Issue by Vi-dot** [bergben/ng2-img-max#18]
Hello,
I have a bug when I try to build my project with angular-cli.
```
ng build
```
return this error : 
```
Metada version mismatch for module img-exif.service.d.ts found version 4, expected 3
```

**Comment by zgliuhouqing** [comment]
metoo，why? Metadata version mismatch for module .......node_modules/ng2-img-max/dist/src/img-exif.service.d.ts, found version 4, expected 3

**Comment by Vi-dot** [comment]
I wrote wrong first, you're right my issue is also about `img-exif.service.d.ts`, not about `ng2-img-max`

**Comment by bergben** [comment]
Hey guys. Please refer to https://github.com/bergben/ng2-img-tools/issues/23 for this issue.

**Comment by SnezanaDichevska** [comment]
ng-img-max doesnt use  img tools? Why do you redirect the issue there?

**Comment by bergben** [comment]
@SnezanaDichevska because the solution is the same: 

> For Angular 4 compatibility downgrade ng2-img-max to version 2.1.6 and ng2-img-tools to version 1.1.0. The recent updates for Angular 5 broke it on 4
