### ISSUE TITLE
EXIF reading issue

### ISSUE THREAD

**Issue by MatissJanis** [bergben/ng2-img-max#19]
Hello,

I'm trying to upload this image:
https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_3.jpg

But EXIF data is failing to be read. This is the error, I believe:

```sh
exif.js:270 Unknown tag: 274
exif.js:270 Unknown tag: 282
exif.js:270 Unknown tag: 283
exif.js:270 Unknown tag: 296
exif.js:270 Unknown tag: 531
```

Result of `Exif.getAllTags(img)` is `{undefined: 1}`.

**Comment by bergben** [comment]
Hi @MatissJanis. Reading EXIF data isn't really the main purpose of this project... The data is only used to keep the right orientation, see #5
For reading exif data I'd recommend using a more specific library like https://github.com/exif-js/exif-js

If you figure out what causes the error though, please let me know!

**Comment by MatissJanis** [comment]
I understand that, but how can this project know the orientation if it fails reading EXIF data? The orientation adjusting is broken. Tested in Chrome 63 on OXS High Sierra in the demo plunkr in README.

If `Exif.getAllTags(img)` is `{undefined: 1}`, then [this line](https://github.com/bergben/ng2-img-max/blob/master/src/img-exif.service.ts#L11) returns `undefined` even though the orientation is in fact set in the EXIF data (see image link above).

**Comment by bergben** [comment]
hmmm everything seems to work fine on Chrome 63 on Windows 10 with that image... 

Also `Exif.getAllTags(img)` is never called in the project, do you mean `Exif.getTag(image, "Orientation");` ?

**Comment by MatissJanis** [comment]
Yeah, `Exif.getAllTags(img)` is never called. I just used that to illustrate the problem that the tags object is empty hence `Exif.getTag(image, "Orientation")` also returns nothing.

**Comment by bergben** [comment]
Thanks for the clarification @MatissJanis and thanks for opening this issue. I am releasing a new version that resolves this issue within the next hour - changing the package to use the above mentioned `exif-js` library.

**Comment by bergben** [comment]
Resolved in version `2.1.13`

**Comment by MatissJanis** [comment]
`ReferenceError: EXIF is not defined`

**Comment by bergben** [comment]
when building or what?
https://github.com/bergben/ng2-img-max/blob/master/src/img-exif.service.ts#L3
https://github.com/bergben/ng2-pica/blob/master/src/img-exif.service.ts#L3

**Comment by MatissJanis** [comment]
This error appears only when I actually attempt to upload/resize the image, not whilst building.

```
ReferenceError: EXIF is not defined
    at eval (webpack-internal:///./node_modules/ng2-img-max/dist/src/img-exif.service.js:13:13)
    at new ZoneAwarePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:887:29)
    at ImgExifService.getOrientedImage (webpack-internal:///./node_modules/ng2-img-max/dist/src/img-exif.service.js:11:22)
    at Image.img.onload [as __zone_symbol__ON_PROPERTYload] (webpack-internal:///./node_modules/ng2-img-max/dist/src/img-maxpx-size.service.js:30:36)
  ...
```

**Comment by MatissJanis** [comment]
I also tried downgrading to `2.1.10` and then it threw the same error in `ng2-pica`

**Comment by ivarvolt** [comment]
I also started receiving the "EXIF is not defined" error. When I call the method resizeImage

adding `<script src="https://cdnjs.cloudflare.com/ajax/libs/exif-js/2.3.0/exif.min.js"></script>` 
cleared the "EXIF is not defined" error and resizeImage started working.

I also tried downgrading to 2.1.5 witch was before stable. But I guess this error comes from a dependency.

**Comment by bergben** [comment]
With the just released ng2-pica 1.2.5. it does at least not break everything anymore if the import of exif-js fails. I don't know why EXIF is not defined there, works the exact same way for `ng2-img-max` ....

**Comment by davidwilcox** [comment]
I upgraded to 2.1.13 and I'm still seeing the error. :(

Adding the script line as ivarvolt indicated above fixes the error for me.

**Comment by davidwilcox** [comment]
I upgraded to 2.1.13 and I'm still seeing the error. I don't know that this is resolved as was indicated above.

Adding the script line as ivarvolt indicated fixes the issue, though for me.

**Comment by ivarvolt** [comment]
As I din't like the script solution, I decided to see what versions of ng2-pica and ng2-img-max, dont produce the EXIF error.

So right now I can use these dependencies:
```
"ng2-img-max": "2.1.9",
"ng2-pica": "1.2.0",
```

**Comment by bergben** [comment]
Hey guys, I finally could spare some minutes to dig into this. Turns out Webpack had some problems with the way I imported `exif-js`. 
Update `ng2-img-max` to 2.1.15 and you should be all set. 

Sorry for the delays and any inconvience caused!

**Comment by akana** [comment]
i updated to 2.1.15 but still get no luck. Below is the error log:
ReferenceError: EXIF is not defined
    at img-exif.service.js:15
    at new t (polyfills.js:3)
    at ImgExifService.getOrientedImage (img-exif.service.js:13)
    at Image.img.onload [as __zone_symbol__ON_PROPERTYload] (img-maxpx-size.service.js:24)

**Comment by akana** [comment]
i can make it works by install ng2-pica as @ivarvolt suggested

**Comment by ivarvolt** [comment]
@akana have you cleared your node_modules folder of given packages?
As the update 2.1.15 fixed the issue for me. And I don't have to specify pica version anymore.

**Comment by akana** [comment]
@ivarvolt After clear node_modules, ng2-img-max runs well without installing ng2-pica. Thank you
