### ISSUE TITLE
Error while uploading Angular 4 server with npm start

### ISSUE THREAD

**Issue by victordeassis** [bergben/ng2-img-max#22]
Hey guys! 

I tried to use the ng2-img-max yesterday, and all run smoothly, but then when I cloned my repo again and tried, it failed with the error:

> ERROR in Error: Metadata version mismatch for module /Users/victordeassis/Documents/GitHub/easygamermvp/node_modules/ng2-img-tools/dist/ng2-img-tools.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/victordeassis/Documents/GitHub/easygamermvp/src/app/app.module.ts, resolving symbol AppModule in /Users/victordeassis/Documents/GitHub/easygamermvp/src/app/app.module.ts

Can you guys help me to solve this?

**Comment by KannanRams** [comment]
Hey guys.. 
me too facing same error

**Comment by DYEWolf** [comment]
stackoverflow says that is a mistake of version, the new version of the img max is for angular 5 and if you have angular 4 throws that issue, know im looking how to install the  version 2.1.0

**Comment by DYEWolf** [comment]
Ok, if u are getting this issue and have angular 4 this works for me:

1. uninstall the package: npm uninstall ng2-img-max --save
2. install this version of ng2 img: npm install ng2-img-max@2.1.2 --save

then ng serve and works.

**Comment by KannanRams** [comment]
Thanks DYEWolf.. it works now..

**Comment by thenb** [comment]
DYEWolf.. Works here!! Thanks!
