### ISSUE TITLE
All resized images have a bitdepth of 32.

### ISSUE THREAD

**Issue by bramdeba** [bergben/ng2-img-max#3]
As a result, images who get resized just a little end up much bigger in filesize than it's original version.

Original (24bit):
![image](https://cloud.githubusercontent.com/assets/14555156/23303654/a60be428-fa95-11e6-9be5-38e9653fd7ba.png)

Resized: (32bit):
![image](https://cloud.githubusercontent.com/assets/14555156/23303664/b56484de-fa95-11e6-858a-69cfe93fed5e.png)

**Comment by bergben** [comment]
This should be fixed with 2.0.1 
Thanks for reporting this issue @bramdeba 👍
