### ISSUE TITLE
Error compiling app

### ISSUE THREAD

**Issue by randomparanoia** [bergben/ng2-img-max#35]
Hello, I'm having this error with new version when starting my app:

```
ERROR in ./node_modules/ng2-img-max/dist/src/ng2-img-max.module.js
Module not found: Error: Can't resolve 'ng2-pica/ng2-pica' in '/home/luis/Desktop/Dev/Code/app/node_modules/ng2-img-max/dist/src'
ERROR in ./node_modules/ng2-img-max/dist/src/img-maxpx-size.service.js
Module not found: Error: Can't resolve 'ng2-pica/ng2-pica' in '/home/luis/Desktop/Dev/Code/rapp/node_modules/ng2-img-max/dist/src'

```
2.1.15 works fine, Angular 6.

Thanks

**Comment by Sampath-Lokuge** [comment]
Can you tell us what is your solution here? I'm having the same error.

**Comment by Sampath-Lokuge** [comment]
Yes, you're right. There is an issue with `2.1.16`. We need to use this `2.1.15` without this `^`,

**Comment by randomparanoia** [comment]
Solution was reverting version to 2.1.15

**Comment by bergben** [comment]
should be fixed with the most recent version now! :)
