### ISSUE TITLE
Bug?  In event "onChange" error photo choice

### ISSUE THREAD

**Issue by fulviocanducci** [bergben/ng2-img-max#36]
In event "onChange" error photo choice

![abce](https://user-images.githubusercontent.com/25593291/43965156-f2146140-9c94-11e8-9056-8aa2961e17cc.png)

Tutorial used: https://alligator.io/angular/resizing-images-in-browser-ng2-img-max/

**Comment by jacksonhart** [comment]
use this thread for the same issue:
https://github.com/bergben/ng2-img-max/issues/38

**Comment by bergben** [comment]
Please refer to #38 as @jacksonhart suggests. The issue should be fixed, closing this.
