### ISSUE TITLE
Remap Exif-JS Usage Until Updated

### ISSUE THREAD

**Issue by ammuench** [bergben/ng2-img-max#41]
The most current version of `exif-js` is `2.3.0` and was updated years ago.  However, the version was uploaded with the following bug: https://github.com/exif-js/exif-js/issues/214

As a result, `ng2-img-max` also will hit that issue when uploading some files. I have fixed this issue in my local by forking the current state of `exif-js` and adding it to my package manifest as a git repo instead, so that the "undefined n" issue is fixed.

`ng2-img-max` should either make the same decision and commit the changes or look for an alternative exif library, as it appears the issue will not be fixed in `exif-js` any time soon (the last update was over a year ago)

**Comment by matteobucci** [comment]
Hi @ammuench, I'm facing the same issue and have reached the same conclusions about the problem. Could you please explain which edit you have made in order to it working? Thanks

**Comment by Methodician** [comment]
So you had to fork the library just to get around this bug? Has anyone found a good EXIF reader library that is kept up to date? All I use this for is to catch orientation issues in my app, and it is such a slog to work through this library...

**Comment by ammuench** [comment]
Yeah, I'm happy to publish the fixes I made once I figure out the licensing in order to unblock people if it would be helpful @Methodician

**Comment by bergben** [comment]
@ammuench If you are interested you may also update ng2-img-max. This library would greatly benefit from an active maintainer. Please let me know if you would be so kind to help out with this and I'd transfer it to you

**Comment by ammuench** [comment]
I don't know how involved I can be, but if you'd like to pass it over to me
I'd be happy to go through the current PRs and clean up what I can!

**Comment by ammuench** [comment]
@bergben Feel free to reach out to me via email if you'd like to discuss further

**Comment by MikeKovarik** [comment]
Hello. exif-js seems to be dead since it hasn't been updated in two years. Because of that I have been developing my own library [exifr](https://github.com/MikeKovarik/exifr) where performance was the main focus. I'd be happy to do a pull request :)

**Comment by bergben** [comment]
@MikeKovarik looks promising! If you would be so kind to open a PR then I'm happy to merge it in and release a new version on npm :)

**Comment by MikeKovarik** [comment]
@bergben awesome! :) So here it is.

I discovered `ng2-img-max` is dependent on `ng2-pica` which also uses exif-js so I thought it'd be better to start there

PR for `ng2-pica`: https://github.com/bergben/ng2-pica/pull/13
PR for `ng2-img-max`: https://github.com/bergben/ng2-img-max/pull/46 but i suppose here we should wait for the `ng2-pica` to be updated first and then raise the version here.

Thank you

**Comment by bergben** [comment]
Merged both PRs, updated ng2-pica version in ng2-img-max 

released on npm 
 - pica 1.3.0
-  ng2-img-max 2.2.0

Thanks @MikeKovarik

**Comment by bergben** [comment]
Please use ng2-img-max 2.2.1, `2.2.0` is broken.
