### ISSUE TITLE
I would like to help you maintain this project

### ISSUE THREAD

**Issue by hiepxanh** [bergben/ng2-img-max#43]
@bergben I would like to help you maintain this project. What should I do? how I can do that?

**Comment by bergben** [comment]
@hiepxanh Glad to hear that! There is a lot that would need to be done.

Most pressing would be an update to support Angular 9 -> Create a running demo. 

ng2-pica needs to be updated too to support the latest version of pica. Best would be to directly use pica.js -> check if types are available

Once that is done, tackling the open issues would be next

Another priority would be to complete observables, adding a default pipeline and linting etc. for this project

**Comment by hiepxanh** [comment]
Yeah, I guess that, I think we need make ng2-pica to work with any pica version. Then I think I can update that to angular 9. I can start working from next week, how should I do that? create a PR or something?

**Comment by bergben** [comment]
Yes please create a PR for moving to pica, then one for angular 9 and so on.

**Comment by hiepxanh** [comment]
yes sir, I got this
