### ISSUE TITLE
Update to Angular 12

### ISSUE THREAD

**Issue by raalbuquerque** [bergben/ng2-img-max#52]
Error to build
./node_modules/ng2-img-max/dist/src/img-exif.service.js:13:6-23 - Error: export 'orientation' (imported as 'exifr') was not found in 'exifr/dist/mini.legacy.umd' (module has no exports)

**Comment by polinasokolenko2711** [comment]
same problem

**Comment by dfa1234** [comment]
Done in #56 and #57- checkout version 2.2.5
