### ISSUE TITLE
ng2-img-max Maintainer

### ISSUE THREAD

**Issue by bergben** [bergben/ng2-img-max#55]
> Hi @bergben, I can't add issues on https://github.com/bergben/ng2-img-max because its archived, so I post here (you can delete after) I wanted to contact you for sharing the repo with you, I think I can help to maintain it. You can write me here or here my mail 

Migrated from https://github.com/bergben/bergben/issues/1

**Comment by dfa1234** [comment]
Then a lot @bergben, I will submit soon a PR for updating to Angular 13 first of all.
