### ISSUE TITLE
Image resize not work in Safari and IE

### ISSUE THREAD

**Issue by Blankarsch** [bergben/ng2-img-max#6]
Great Module! But unfortunately image resize not work in Safari and IE. A fix would be awesome! ;)

**Comment by bergben** [comment]
Hey there @Blankarsch 
I couldn't reproduce this in IE10 + 11... Please make sure you are including core-js. 
See https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by RathodGirish** [comment]
I am also getting same error when try to implement in safari browser:

  {
    "resizedFile": {},
    "reason": {
      "line": 20562,
      "column": 45,
      "sourceURL": "http://192.168.1.3:4200/1.chunk.js",
      "__zone_symbol__currentTask": {
        "type": "microTask",
        "state": "notScheduled",
        "source": "Promise.then",
        "zone": "<root>",
        "cancelFn": null,
        "runCount": 0
      }
    },
    "error": "PICA_ERROR"
  }


Any suggestions?

**Comment by bergben** [comment]
See https://github.com/bergben/ng2-img-tools/issues/7

**Comment by bergben** [comment]
Version 2.1.4 should resolve this issue: https://github.com/bergben/ng2-img-max/releases/tag/2.1.4

**Comment by RathodGirish** [comment]
Hey great thanks.
I will get latest version using this command right?
 `npm install ng2-img-tools --save `

**Comment by bergben** [comment]
yes, 1.0.4 is the most recent of `ng2-img-tools`. :)
