### ISSUE TITLE
No provider for ........Service

### ISSUE THREAD

**Issue by ivaro18** [bergben/ng2-img-max#9]
Hi, 
After installing this library in my project and trying to call `.compressImage`, I got multiple exceptions.
```
No provider for ImgMaxSizeService
No provider for ImgExifService
No provider for ImgMaxPXSizeService
```

Now I could fix all these by setting them in the `providers` block in my `@NgModule` declaration

The problem I encounter now is that it complains:

```
No provider for Ng2PicaService
```

Which is not a class exported by the library. How can I fix this issue?

**Comment by bergben** [comment]
@ivaro18 Have you tried to completely remove the package and reinstall it?
`npm uninstall --save ng2-img-max`
`npm cache clear` 
`npm i --save ng2-img-max`
